services:
  backend:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: QIQuiz
    environment:
      APP_PORT: 3333
      CORS_ORIGINS: http://localhost:3333
      DATABASE_URL: mysql://root:123123@database:3306/qiquiz
      DATABASE_MAX_CONNECTIONS: 2
      DATABASE_MIN_CONNECTIONS: 1
      JWT_SECRET: QIQuiz
    ports:
      - "3333:3333"
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_DATABASE: qiquiz
      MARIADB_ROOT_PASSWORD: 123123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data: