//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "question")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub text: String,
    pub id_quiz: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::alternative::Entity")]
    Alternative,
    #[sea_orm(
        belongs_to = "super::quiz::Entity",
        from = "Column::IdQuiz",
        to = "super::quiz::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Quiz,
}

impl Related<super::alternative::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Alternative.def()
    }
}

impl Related<super::quiz::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Quiz.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
